networks:
  network_internal:
    external: true
    name: ${NETWORK_INTERNAL}
services:
  automediaorganizer:
    image: timmy93/automediaorganizer:latest
    environment:
      TZ: ${TZ}
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
    volumes:
      - ${AMO_CONFIG}/config.toml:/app/Config/config.toml
      - ${AMO_CONFIG}/scan_config.toml:/app/Config/scan_config.toml
      - ${AMO_CONFIG}/AutoMediaOrganizer.log:/app/Config/AutoMediaOrganizer.log
      - ${MEDIA_DIR}:/media
    restart: unless-stopped
    networks:
      - network_internal
