[project]
name = "automediaorganizer"
version = "0.1.0"
description = "Automated Media Organizer for media based on config files"
requires-python = ">=3.12"
dependencies = [
    "requests==2.32.5",
    "pymysql>=1.1.0",
]
